### ISSUE TITLE
Failing when trying to run a git command

### ISSUE THREAD

**Issue by diegoaguilar** [IndigoUnited/node-cross-spawn#22]
Using yeoman, which uses node-cross-spawn as dependency, I'm trying to start a git repo when scaffolding an application with a yeoman custom generator, this is what I got at the `install` step:

      install: function () {
        this.installDependencies();
        this.spawnCommand('npm', ['i', '--save' , 'express', 'mongodb', 'mongoose', 'lodash', 'bluebird', 'async', 'morgan']);
        this.spawnCommand('git' ['init']); // Here it fails
        this.spawnCommand('git', ['add', '.']);
        this.spawnCommand('git', ['commit', '-am', '"yo scaffolded app"']);
      }

However when trying to run this I get:

    events.js:85
          throw er; // Unhandled 'error' event
                ^
    TypeError: Bad argument
        at TypeError (native)
        at ChildProcess.spawn (child_process.js:1136:26)
        at Object.exports.spawn (child_process.js:995:9)
        at spawn (/storage/home/dev/generator-koala/node_modules/yeoman-generator/node_modules/cross-spawn/index.js:87:19)
        at spawnCommand (/storage/home/dev/generator-koala/node_modules/yeoman-generator/lib/actions/spawn_command.js:17:10)
        at module.exports.yeoman.generators.Base.extend.install (/storage/home/dev/generator-koala/generators/app/index.js:72:10)
        at /storage/home/dev/generator-koala/node_modules/yeoman-generator/lib/base.js:421:16
        at processImmediate [as _immediateCallback] (timers.js:367:17)

I do have git installed, how should I fix this?

**Comment by satazor** [comment]
```
 this.spawnCommand('git' ['init']); // Here it fails
```

You forgot a comma, it should be.

```
 this.spawnCommand('git', ['init']); // Here it fails
```
